name: CI

on:
  push:
    paths: path/to/not_found

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: docker-compose version
